/// Flutter icons BeerIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BeerIcon
///      fonts:
///       - asset: fonts/BeerIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BeerIcon {
  BeerIcon._();

  static const _kFontFam = 'BeerIcon';
  static const _kFontPkg = null;

  static const IconData instagram = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beerglass = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_empty = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_filled = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_empty = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_empty = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_filled = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer_empty = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer_filled = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_empty = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasted_empty = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasted_full = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
